name: "Deploy to NuGet"

on:
  workflow_dispatch:
    inputs:
        branch:
          description: 'Branch to deploy'
          required: true
          default: 'main'

#env:

jobs:
  build:
    runs-on: 'windows-latest'
    
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v4

    - name: 'Install dotnet'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: 'Restore dependencies'
      run: dotnet restore 

    - name: 'Build'
      run: dotnet build  --no-restore --configuration Release

  publish:
     runs-on: 'windows-latest'
     needs: build
     
     steps:
        - name: Checkout code
          uses: actions/checkout@v4
          
        - name: Setup .NET
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: '8.0.x'

        - name: Add nuget source
          run: dotnet nuget add source --username Dom21Nguyen --password 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 --store-password-in-clear-text --name github "https://nuget.pkg.github.com/OWNER/index.json"
        - name: 'Pack project'
    
        - name: Restore dependencies
          run: dotnet restore
      
        - name: Pack application
          run: dotnet pack --configuration Release -output ./artifacts -p:PackageVersion=1.1.0
      
        - name: Puplish to GitHub Packages
          run: dotnet nuget push ./artifacts/*.nupkg --source "" --api-key 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
